package com.devilGhost.ResponseHub.models;

import lombok.Data;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Map;

@Data
@Document(collection = "callRecordModel")
public class CallRecordModel {
    @Id
    private ObjectId id;// auto generated by mongodb
    private String time;
    private String method;
    private String endpoint;
    private String status;
    private Map<Object,Object> requestBody;
    private Map<Object,Object> responseBody;
}
