package com.devilGhost.ResponseHub.models;

import lombok.Data;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Map;


@Data
@Document(collection = "fixedRequestModel")
public class FixedRequestModel {
    @Id
    private ObjectId id; // auto generated by mongodb
    private String endpoint;
    private String method;
    private Map<Object,Object> responseBody;
}
