package com.devilGhost.ResponseHub.models;

import lombok.Data;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.mapping.Document;


@Data
@Document(collection = "fixedRequest")
@CompoundIndex(
        name = "indexingForFixedRequest",
        def = "{'username': 1, 'method': 1, 'endpoint': 1}",
        unique = true
)
public class FixedEndpoint {
    @Id
    private ObjectId id; // auto generated by mongodb

    // since multiple users can have same endpoint and method,
    // indexing includes 3 things for uniqueness
    // (username, method, endpoint)
    // this will allow to search for fixedRequests of a user from collection
    // via username search

    private String username;
    private String method;
    private String endpoint;
    private int statusCode;
    private Object responseBody;

}
