package com.devilGhost.ResponseHub.models;

import lombok.Data;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.Map;

@Data
@Document(collection = "record")
@CompoundIndex(
        name = "indexingForRecords",
        def = "{'username': 1, 'time': 1}",
        unique = true
)
public class Record {

    @Id
    private ObjectId id;// auto generated by mongodb

    private String username;
    private Instant time;// Instant will be use-full in pagination and searching

    private String method;
    private String endpoint;
    private int statusCode;

    private Object requestBody;
    private Object responseBody;
}
