package com.devilGhost.ResponseHub.models;


import lombok.Data;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

@Data
@Document(collection = "userModel")
public class UserModel {
    @Id
    private ObjectId id; // auto generated by mongodb
    @Indexed(unique = true)
    private String username;
    @Indexed(unique = true)
    private String apiKey;
    private String password;
    private String name;
    @DBRef
    private List<FixedRequestModel> fixedRequestModels;
    @DBRef
    private List<CallRecordModel> callRecordModels;
}
