package com.devilGhost.ResponseHub.models;


import lombok.Data;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;


@Data
@Document(collection = "user")
public class UserEntity {
    // named it UserEntity and not User to distinguish between SpringSecurity's User and this one
    @Id
    private ObjectId id; // auto generated by mongodb

    @Indexed(unique = true)
    private String username;

    @Indexed(unique = true)
    private String apiKey;

    private String password;
    private String name;

}
