# spring variables
spring.application.name=responseHub
server.port=5000

# mongodb variables
spring.data.mongodb.uri=mongodb+srv://businesskartik3y:36Cd9VWRgS8b2XWs@responsehub.hxjjt0h.mongodb.net/?retryWrites=true&w=majority&appName=ResponseHub
spring.data.mongodb.database=ResponseHub
spring.data.mongodb.auto-index-creation=true

# jwt variables (24 hr time for expiration)
jwt.secretKey=ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmFhYWJiYmNjY2RkZGVlZmZmZ2dnZ2cq
jwt.expirationTime=86400000
